# Generated by Django 4.0.3 on 2023-02-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name_plural': 'Adding Record'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
    ]
